const { withGradleProperties } = require("@expo/config-plugins");

/**
 * Durable JDK-21 pin for Android native builds.
 *
 * Android Studio's bundled JDK 25 breaks React Native's CMake configure tasks
 * ("restricted method in java.lang.System has been called" → configureCMake*
 * FAILED). The Gradle *daemon* JVM must be JDK 21 (LTS). Pinning
 * `org.gradle.java.home` in android/gradle.properties works, but android/ is
 * gitignored and regenerated by `expo prebuild`, so a manual pin does not
 * survive a fresh checkout. Config plugins run on every prebuild, so this makes
 * the pin durable.
 *
 * Portable by design: the path differs per machine/CI, so it is read from the
 * LIFEPILOT_ANDROID_JAVA_HOME env var rather than hardcoded. If the var is not
 * set, the plugin is a no-op (machines that already default to JDK 21 build
 * fine untouched).
 *
 *   export LIFEPILOT_ANDROID_JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-21.jdk/Contents/Home
 *   npx expo prebuild -p android
 */
module.exports = function withAndroidJdkHome(config) {
  return withGradleProperties(config, (cfg) => {
    const javaHome = process.env.LIFEPILOT_ANDROID_JAVA_HOME;
    if (!javaHome) {
      return cfg;
    }

    cfg.modResults = cfg.modResults.filter(
      (item) =>
        !(item.type === "property" && item.key === "org.gradle.java.home")
    );

    cfg.modResults.push({
      type: "property",
      key: "org.gradle.java.home",
      value: javaHome,
    });

    return cfg;
  });
};
