# Generated by Django 6.0.6 on 2026-08-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('task_start', 'Task Start'), ('deadline', 'Deadline'), ('daily_review', 'Daily Review')], max_length=16),
        ),
    ]
