# Generated by Django 6.0.6 on 2026-08-02 16:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=6)),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done')], default='open', max_length=4)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('ai', 'Ai'), ('email', 'Email'), ('scan', 'Scan')], default='manual', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='users.userprofile')),
            ],
            options={
                'ordering': ['due_date', '-created_at'],
            },
        ),
    ]
