# Generated by Django 6.0.6 on 2026-08-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
