# Generated by Django 6.0.6 on 2026-08-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcal', '0002_pendingoauth'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim', models.CharField(max_length=64, unique=True)),
                ('token_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='pendingoauth',
            name='code_verifier',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
