# Generated by Django 6.0.6 on 2026-08-02 16:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopilotMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=9)),
                ('content', models.TextField()),
                ('context_ref', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='users.userprofile')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('summary_text', models.TextField()),
                ('best_focus_window', models.CharField(blank=True, max_length=32)),
                ('meeting_count', models.PositiveSmallIntegerField(default=0)),
                ('task_due_count', models.PositiveSmallIntegerField(default=0)),
                ('generated_by', models.CharField(choices=[('ai', 'Ai'), ('fallback', 'Fallback')], default='fallback', max_length=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='users.userprofile')),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
